// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NeedInfoMessage.proto

package org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java;

public final class NeedInfoMessage {
  private NeedInfoMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NeedsInfoMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string message = 1;
    boolean hasMessage();
    String getMessage();
    
    // required .org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedsInfoMessage.NeedType needType = 2;
    boolean hasNeedType();
    org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.NeedType getNeedType();
  }
  public static final class NeedsInfoMessage extends
      com.google.protobuf.GeneratedMessage
      implements NeedsInfoMessageOrBuilder {
    // Use NeedsInfoMessage.newBuilder() to construct.
    private NeedsInfoMessage(Builder builder) {
      super(builder);
    }
    private NeedsInfoMessage(boolean noInit) {}
    
    private static final NeedsInfoMessage defaultInstance;
    public static NeedsInfoMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public NeedsInfoMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_org_haw_cas_Adapters_RTCToDataMinerAdapter_Implementation_data_messageTyp_java_NeedsInfoMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_org_haw_cas_Adapters_RTCToDataMinerAdapter_Implementation_data_messageTyp_java_NeedsInfoMessage_fieldAccessorTable;
    }
    
    public enum NeedType
        implements com.google.protobuf.ProtocolMessageEnum {
      Food(0, 1),
      Water(1, 2),
      Shelter(2, 3),
      MedicalCare(3, 4),
      Helper(4, 5),
      ;
      
      public static final int Food_VALUE = 1;
      public static final int Water_VALUE = 2;
      public static final int Shelter_VALUE = 3;
      public static final int MedicalCare_VALUE = 4;
      public static final int Helper_VALUE = 5;
      
      
      public final int getNumber() { return value; }
      
      public static NeedType valueOf(int value) {
        switch (value) {
          case 1: return Food;
          case 2: return Water;
          case 3: return Shelter;
          case 4: return MedicalCare;
          case 5: return Helper;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<NeedType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<NeedType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NeedType>() {
              public NeedType findValueByNumber(int number) {
                return NeedType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final NeedType[] VALUES = {
        Food, Water, Shelter, MedicalCare, Helper, 
      };
      
      public static NeedType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private NeedType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedsInfoMessage.NeedType)
    }
    
    private int bitField0_;
    // required string message = 1;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          message_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedsInfoMessage.NeedType needType = 2;
    public static final int NEEDTYPE_FIELD_NUMBER = 2;
    private org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.NeedType needType_;
    public boolean hasNeedType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.NeedType getNeedType() {
      return needType_;
    }
    
    private void initFields() {
      message_ = "";
      needType_ = org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.NeedType.Food;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNeedType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, needType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, needType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_org_haw_cas_Adapters_RTCToDataMinerAdapter_Implementation_data_messageTyp_java_NeedsInfoMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_org_haw_cas_Adapters_RTCToDataMinerAdapter_Implementation_data_messageTyp_java_NeedsInfoMessage_fieldAccessorTable;
      }
      
      // Construct using org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        needType_ = org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.NeedType.Food;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.getDescriptor();
      }
      
      public org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage getDefaultInstanceForType() {
        return getDefaultInstance();
      }
      
      public org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage build() {
        org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage buildPartial() {
        org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage result = new org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.needType_ = needType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage) {
          return mergeFrom((org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (other.hasNeedType()) {
          setNeedType(other.getNeedType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMessage()) {
          
          return false;
        }
        if (!hasNeedType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              message_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.NeedType value = org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.NeedType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                needType_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string message = 1;
      private java.lang.Object message_ = "";
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      void setMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
      }
      
      // required .org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedsInfoMessage.NeedType needType = 2;
      private org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.NeedType needType_ = org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.NeedType.Food;
      public boolean hasNeedType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.NeedType getNeedType() {
        return needType_;
      }
      public Builder setNeedType(org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.NeedType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        needType_ = value;
        onChanged();
        return this;
      }
      public Builder clearNeedType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        needType_ = org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.NeedType.Food;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedsInfoMessage)
    }
    
    static {
      defaultInstance = new NeedsInfoMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedsInfoMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_haw_cas_Adapters_RTCToDataMinerAdapter_Implementation_data_messageTyp_java_NeedsInfoMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_haw_cas_Adapters_RTCToDataMinerAdapter_Implementation_data_messageTyp_java_NeedsInfoMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025NeedInfoMessage.proto\022Norg.haw.cas.Ada" +
      "pters.RTCToDataMinerAdapter.Implementati" +
      "on.data.messageTyp.java\"\353\001\n\020NeedsInfoMes" +
      "sage\022\017\n\007message\030\001 \002(\t\022{\n\010needType\030\002 \002(\0162" +
      "i.org.haw.cas.Adapters.RTCToDataMinerAda" +
      "pter.Implementation.data.messageTyp.java" +
      ".NeedsInfoMessage.NeedType\"I\n\010NeedType\022\010" +
      "\n\004Food\020\001\022\t\n\005Water\020\002\022\013\n\007Shelter\020\003\022\017\n\013Medi" +
      "calCare\020\004\022\n\n\006Helper\020\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_haw_cas_Adapters_RTCToDataMinerAdapter_Implementation_data_messageTyp_java_NeedsInfoMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_haw_cas_Adapters_RTCToDataMinerAdapter_Implementation_data_messageTyp_java_NeedsInfoMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_haw_cas_Adapters_RTCToDataMinerAdapter_Implementation_data_messageTyp_java_NeedsInfoMessage_descriptor,
              new java.lang.String[] { "Message", "NeedType", },
              org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.class,
              org.haw.cas.Adapters.RTCToDataMinerAdapter.Implementation.data.messageTyp.java.NeedInfoMessage.NeedsInfoMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
