// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/common/UpdateUserPositionsMessage.proto

package org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder;

public final class UpdateUserPositionsMessage {
  private UpdateUserPositionsMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UpdateUserPositionsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string requestId = 1;
    boolean hasRequestId();
    String getRequestId();
    
    // required .org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinates center = 2;
    boolean hasCenter();
    org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates getCenter();
    org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinatesOrBuilder getCenterOrBuilder();
    
    // required float radius = 3;
    boolean hasRadius();
    float getRadius();
    
    // required int64 oldest = 4;
    boolean hasOldest();
    long getOldest();
  }
  public static final class UpdateUserPositions extends
      com.google.protobuf.GeneratedMessage
      implements UpdateUserPositionsOrBuilder {
    // Use UpdateUserPositions.newBuilder() to construct.
    private UpdateUserPositions(Builder builder) {
      super(builder);
    }
    private UpdateUserPositions(boolean noInit) {}
    
    private static final UpdateUserPositions defaultInstance;
    public static UpdateUserPositions getDefaultInstance() {
      return defaultInstance;
    }
    
    public UpdateUserPositions getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.internal_static_org_haw_cas_Adapters_AkkaAdapter_Implementation_ProtoMsgBuilder_UpdateUserPositions_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.internal_static_org_haw_cas_Adapters_AkkaAdapter_Implementation_ProtoMsgBuilder_UpdateUserPositions_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string requestId = 1;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private java.lang.Object requestId_;
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          requestId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinates center = 2;
    public static final int CENTER_FIELD_NUMBER = 2;
    private org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates center_;
    public boolean hasCenter() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates getCenter() {
      return center_;
    }
    public org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinatesOrBuilder getCenterOrBuilder() {
      return center_;
    }
    
    // required float radius = 3;
    public static final int RADIUS_FIELD_NUMBER = 3;
    private float radius_;
    public boolean hasRadius() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getRadius() {
      return radius_;
    }
    
    // required int64 oldest = 4;
    public static final int OLDEST_FIELD_NUMBER = 4;
    private long oldest_;
    public boolean hasOldest() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getOldest() {
      return oldest_;
    }
    
    private void initFields() {
      requestId_ = "";
      center_ = org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates.getDefaultInstance();
      radius_ = 0F;
      oldest_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCenter()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRadius()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOldest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCenter().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, center_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, radius_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, oldest_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, center_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, radius_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, oldest_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.internal_static_org_haw_cas_Adapters_AkkaAdapter_Implementation_ProtoMsgBuilder_UpdateUserPositions_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.internal_static_org_haw_cas_Adapters_AkkaAdapter_Implementation_ProtoMsgBuilder_UpdateUserPositions_fieldAccessorTable;
      }
      
      // Construct using org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCenterFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        requestId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (centerBuilder_ == null) {
          center_ = org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates.getDefaultInstance();
        } else {
          centerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        radius_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        oldest_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions.getDescriptor();
      }
      
      public org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions getDefaultInstanceForType() {
        return org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions.getDefaultInstance();
      }
      
      public org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions build() {
        org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions buildPartial() {
        org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions result = new org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (centerBuilder_ == null) {
          result.center_ = center_;
        } else {
          result.center_ = centerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.radius_ = radius_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.oldest_ = oldest_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions) {
          return mergeFrom((org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions other) {
        if (other == org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasCenter()) {
          mergeCenter(other.getCenter());
        }
        if (other.hasRadius()) {
          setRadius(other.getRadius());
        }
        if (other.hasOldest()) {
          setOldest(other.getOldest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRequestId()) {
          
          return false;
        }
        if (!hasCenter()) {
          
          return false;
        }
        if (!hasRadius()) {
          
          return false;
        }
        if (!hasOldest()) {
          
          return false;
        }
        if (!getCenter().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              requestId_ = input.readBytes();
              break;
            }
            case 18: {
              org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates.Builder subBuilder = org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates.newBuilder();
              if (hasCenter()) {
                subBuilder.mergeFrom(getCenter());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCenter(subBuilder.buildPartial());
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              radius_ = input.readFloat();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              oldest_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string requestId = 1;
      private java.lang.Object requestId_ = "";
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRequestId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      void setRequestId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
      }
      
      // required .org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinates center = 2;
      private org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates center_ = org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates, org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates.Builder, org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinatesOrBuilder> centerBuilder_;
      public boolean hasCenter() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates getCenter() {
        if (centerBuilder_ == null) {
          return center_;
        } else {
          return centerBuilder_.getMessage();
        }
      }
      public Builder setCenter(org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates value) {
        if (centerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          center_ = value;
          onChanged();
        } else {
          centerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setCenter(
          org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates.Builder builderForValue) {
        if (centerBuilder_ == null) {
          center_ = builderForValue.build();
          onChanged();
        } else {
          centerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeCenter(org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates value) {
        if (centerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              center_ != org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates.getDefaultInstance()) {
            center_ =
              org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates.newBuilder(center_).mergeFrom(value).buildPartial();
          } else {
            center_ = value;
          }
          onChanged();
        } else {
          centerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearCenter() {
        if (centerBuilder_ == null) {
          center_ = org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates.getDefaultInstance();
          onChanged();
        } else {
          centerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates.Builder getCenterBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCenterFieldBuilder().getBuilder();
      }
      public org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinatesOrBuilder getCenterOrBuilder() {
        if (centerBuilder_ != null) {
          return centerBuilder_.getMessageOrBuilder();
        } else {
          return center_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates, org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates.Builder, org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinatesOrBuilder> 
          getCenterFieldBuilder() {
        if (centerBuilder_ == null) {
          centerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates, org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinates.Builder, org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.GeoCoordinatesOrBuilder>(
                  center_,
                  getParentForChildren(),
                  isClean());
          center_ = null;
        }
        return centerBuilder_;
      }
      
      // required float radius = 3;
      private float radius_ ;
      public boolean hasRadius() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getRadius() {
        return radius_;
      }
      public Builder setRadius(float value) {
        bitField0_ |= 0x00000004;
        radius_ = value;
        onChanged();
        return this;
      }
      public Builder clearRadius() {
        bitField0_ = (bitField0_ & ~0x00000004);
        radius_ = 0F;
        onChanged();
        return this;
      }
      
      // required int64 oldest = 4;
      private long oldest_ ;
      public boolean hasOldest() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getOldest() {
        return oldest_;
      }
      public Builder setOldest(long value) {
        bitField0_ |= 0x00000008;
        oldest_ = value;
        onChanged();
        return this;
      }
      public Builder clearOldest() {
        bitField0_ = (bitField0_ & ~0x00000008);
        oldest_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositions)
    }
    
    static {
      defaultInstance = new UpdateUserPositions(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositions)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_haw_cas_Adapters_AkkaAdapter_Implementation_ProtoMsgBuilder_UpdateUserPositions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_haw_cas_Adapters_AkkaAdapter_Implementation_ProtoMsgBuilder_UpdateUserPositions_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0messages/common/UpdateUserPositionsMes" +
      "sage.proto\022?org.haw.cas.Adapters.AkkaAda" +
      "pter.Implementation.ProtoMsgBuilder\032+mes" +
      "sages/common/GeoCoordinatesMessage.proto" +
      "\"\251\001\n\023UpdateUserPositions\022\021\n\trequestId\030\001 " +
      "\002(\t\022_\n\006center\030\002 \002(\0132O.org.haw.cas.Adapte" +
      "rs.AkkaAdapter.Implementation.ProtoMsgBu" +
      "ilder.GeoCoordinates\022\016\n\006radius\030\003 \002(\002\022\016\n\006" +
      "oldest\030\004 \002(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_haw_cas_Adapters_AkkaAdapter_Implementation_ProtoMsgBuilder_UpdateUserPositions_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_haw_cas_Adapters_AkkaAdapter_Implementation_ProtoMsgBuilder_UpdateUserPositions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_haw_cas_Adapters_AkkaAdapter_Implementation_ProtoMsgBuilder_UpdateUserPositions_descriptor,
              new java.lang.String[] { "RequestId", "Center", "Radius", "Oldest", },
              org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions.class,
              org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.UpdateUserPositionsMessage.UpdateUserPositions.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.haw.cas.Adapters.AkkaAdapter.Implementation.ProtoMsgBuilder.GeoCoordinatesMessage.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
